### ISSUE TITLE
19-10-04 07:03:55 WARNING (MainThread) [hassio.api.ingress] No valid ingress session

### ISSUE THREAD

**Issue by thundergreen** [hassio-addons/addon-home-panel#38] opened 2019-10-04 07:35 UTC
# Problem/Motivation
I have a toucschreen attached to my haassio machine to control the HomePanel Dashboard. After a while my logs get flooded with:

```
19-10-04 07:03:55 WARNING (MainThread) [hassio.api.ingress] No valid ingress session d05991b3b6edcbd22413040d211e303709f296040e9c656d66f9eea26cbef1fa752fc9360e1be2bb669adc8e786d9a484431b70b031172f20869a4d4e14ecfb7
```

And indeed the HomePanel does not response anymore. Either the screen is black (but not blackscreen) or it just won't load the content of my created dashboard.
> (Why the issue was filed)

## Expected behavior
No blackscreen anymore :)

> (What you expected to happen)

## Actual behavior
After a while the Screen attached to HassIO machine goes dark (no blackscreen!) and unresponsive. I have to close the browseer and restart it manually and it work for a while
> (What actually happened)

## Steps to reproduce
open HomePanel and wait a few hours

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by timmo001** [comment] 2019-10-04 14:13
I've recently been having issues with ingress/hassio. A restart of the server seemed to solve my issues.

I do not think this is an add-on specific issue, unless others can reproduce this issue. Hassio ingress / Home Assistant may time out your session after a time, but this is likely an isolated case imho.

**Comment by timmo001** [comment] 2019-10-18 22:28
As above, this issue seems to be isolated, so I will close this one

**Closed by timmo001** 2019-10-18 22:28 UTC
Labels: Status: Triage

**Comment by PatricDahl** [comment] 2019-10-21 21:02
I suffer same issus as mention above.

9-10-21 20:43:06 WARNING (MainThread) [hassio.api.ingress] No valid ingress session d1fd6f3d1a628944019f05d93d293f5d4161e769c15aa6129948559f3c057c7ea81560cf81ca35430442fc8035558f8f5b3bc42995c4d27d4e08d60ebea95d99

After some time system is unresponsive to web requests and rebbot needed to be able use again.

Any help is appreciated.

**Comment by thundergreen** [comment] 2019-10-22 15:55
@PatricDahl  That's why i run HomePanel in native Docker :)
